Title: Assignment 5

Question 1: Read the “daily_show_guests.csv” file from GitHub in the R and print the first 10 records

In [59]:
data <- read.csv("./daily_show_guests.csv")
print(head(data, 10))

   YEAR GoogleKnowlege_Occupation    Show    Group   Raw_Guest_List
1  1999                     actor 1/11/99   Acting   Michael J. Fox
2  1999                  Comedian 1/12/99   Comedy  Sandra Bernhard
3  1999        television actress 1/13/99   Acting    Tracey Ullman
4  1999              film actress 1/14/99   Acting Gillian Anderson
5  1999                     actor 1/18/99   Acting David Alan Grier
6  1999                     actor 1/19/99   Acting  William Baldwin
7  1999           Singer-lyricist 1/20/99 Musician    Michael Stipe
8  1999                     model 1/21/99    Media   Carmen Electra
9  1999                     actor 1/25/99   Acting  Matthew Lillard
10 1999         stand-up comedian 1/26/99   Comedy      David Cross

Question 2: Display the “column names” of the table and rename the columns as: - year: YEAR; job: GoogleKnowlege_Occupation; date: Show; category: Group; guest_name: Raw_Guest_List.

In [60]:
data <- rename(data, "year" = "YEAR", "job" = "GoogleKnowlege_Occupation")
# data <- rename(data, "job" = "GoogleKnowlege_Occupation")
# data <- rename(data, "date" = "Show")
# data <- rename(data, "category" = "Group")
# data <- rename(data, "guest_name" = "Raw_Guest_List")
print(head(data))

  year                job    Show  Group   Raw_Guest_List
1 1999              actor 1/11/99 Acting   Michael J. Fox
2 1999           Comedian 1/12/99 Comedy  Sandra Bernhard
3 1999 television actress 1/13/99 Acting    Tracey Ullman
4 1999       film actress 1/14/99 Acting Gillian Anderson
5 1999              actor 1/18/99 Acting David Alan Grier
6 1999              actor 1/19/99 Acting  William Baldwin

Question 3: Create a report having year, date, and guest_name.`

In [38]:
report <- data.frame(data['year'], data['date'], data['guest_name'])
head(report)

  year date    guest_name
1 1999 1/11/99 Michael J. Fox
2 1999 1/12/99 Sandra Bernhard
3 1999 1/13/99 Tracey Ullman
4 1999 1/14/99 Gillian Anderson
5 1999 1/18/99 David Alan Grier
6 1999 1/19/99 William Baldwin

Question 4: Use “select” (dplyr) function to print all the record except “year”

In [40]:
select(data, job, date, category, guest_name)

     job                        date     category   guest_name
1    actor                      1/11/99  Acting     Michael J. Fox
2    Comedian                   1/12/99  Comedy     Sandra Bernhard
3    television actress         1/13/99  Acting     Tracey Ullman
4    film actress               1/14/99  Acting     Gillian Anderson
5    actor                      1/18/99  Acting     David Alan Grier
6    actor                      1/19/99  Acting     William Baldwin
7    Singer-lyricist            1/20/99  Musician   Michael Stipe
8    model                      1/21/99  Media      Carmen Electra
9    actor                      1/25/99  Acting     Matthew Lillard
10   stand-up comedian          1/26/99  Comedy     David Cross
11   actress                    1/27/99  Acting     Yasmine Bleeth
12   actor                      1/28/99  Acting     D. L. Hughley
13   television actress         10/18/99 Acting     Rebecca Gayheart
14   Comedian                   10/19/99 Comedy     Steven Wright
15   actress                    10/20/99 Acting     Amy Brenneman
16   actress                    10/21/99 Acting     Melissa Gilbert
17   actress                    10/25/99 Acting     Cathy Moriarty
18   comedian                   10/26/99 Comedy     Louie Anderson
19   actress                    10/27/99 Acting     Sarah Michelle Gellar
20   Singer-songwriter          10/28/99 Musician   Melanie C
21   actor                      10/4/99  Acting     Greg Proops
22   television personality     10/5/99  Media      Maury Povich
23   actress                    10/6/99  Acting     Brooke Shields
24   Comic                      10/7/99  Comedy     Molly Shannon
25   actor                      11/1/99  Acting     Chris O'Donnell
26   actress                    11/15/99 Acting     Christina Ricci
27   Singer-songwriter          11/16/99 Musician   Tori Amos
28   actress                    11/17/99 Acting     Yasmine Bleeth
29   comedian                   11/18/99 Comedy     Bill Maher
30   actress                    11/2/99  Acting     Jennifer Love Hewitt
⋮    ⋮                          ⋮        ⋮          ⋮
2664 stand-up comedian          6/10/15  Comedy     Colin Quinn
2665 actor                      6/11/15  Acting     Mark Ruffalo
2666 screenwriter               6/15/15  Media      Judd Apatow
2667 actor                      6/16/15  Acting     Aziz Ansari
2668 us president               6/17/15  Politician Bill Clinton
2669 activist                   6/18/15  Advocacy   Malala Yousafzai
2670 nyc mayor                  6/2/15   Politician Bill de Blasio
2671 united states senator      6/22/15  Politician Al Franken
2672 television Series Creator  6/23/15  Media      Seth MacFarlane
2673 legal analyst              6/24/15  Misc       Andrew Napolitano
2674 Comedian                   6/25/15  Comedy     Richard Lewis
2675 actress                    6/29/15  Acting     Taylor Schilling
2676 actress                    6/3/15   Acting     Melissa McCarthy
2677 actor                      6/30/15  Acting     Jon Hamm
2678 actor                      6/4/15   Acting     Steve Buscemi
2679 First Minister of Scotland 6/8/15   Politician Nicola Sturgeon
2680 actor                      6/9/15   Acting     Nick Offerman
2681 United States Senator      7/1/15   Politician Kirsten Gillibrand
2682 Author                     7/2/15   Media      Sarah Vowell
2683 actor                      7/20/15  Acting     Paul Rudd
2684 us president               7/21/15  Politician Barack Obama
2685 actor                      7/22/15  Acting     Jake Gyllenhaal
2686 Writer                     7/23/15  Media      Ta-Nehisi Coates
2687 author                     7/27/15  Media      David McCullough
2688 actor                      7/28/15  Acting     Tom Cruise
2689 biographer                 7/29/15  Media      Doris Kearns Goodwin
2690 director                   7/30/15  Media      J. J. Abrams
2691 stand-up comedian          8/3/15   Comedy     Amy Schumer
2692 actor                      8/4/15   Acting     Denis Leary
2693 comedian                   8/5/15   Comedy     Louis C.K.

Question 5: Extract the list of peoples who are “actor” only name is “ABC”

In [51]:
filtered_data <- filter(data, job == 'actor')
select(filtered_data, guest_name)

    guest_name
1   Michael J. Fox
2   David Alan Grier
3   William Baldwin
4   Matthew Lillard
5   D. L. Hughley
6   Greg Proops
7   Chris O'Donnell
8   Michael Boatman
9   David Boreanaz
10  Paul Rudd
11  Rob Schneider
12  Mike Judge
13  Dave Foley
14  Jerry O'Connell
15  Brendan Fraser
16  Hootie & the Blowfish, Billy Crystal
17  Frank DeCaro's Oscar Special, John Larroquette
18  Joseph Gordon-Levitt
19  Eric McCormack
20  Omar Epps
21  Ryan Phillippe
22  Ian McKellen
23  Jon Voight
24  Stephen Baldwin
25  Ernie Hudson
26  Jackie Chan
27  Rob Estes
28  Seth Green
29  Thomas Gibson
30  Ted Danson
⋮   ⋮
567 Jim Parsons
568 James McAvoy
569 Seth Rogen
570 Christopher Walken
571 Kevin Hart
572 Robert De Niro
573 Tom Cruise
574 George Takei
575 Elisabeth Moss
576 Bill Hader
577 Ben Affleck
578 Oscar Isaac
579 Colin Firth
580 Martin Short
581 Bob Odenkirk
582 Rob Corddry
583 Kevin Hart
584 Will Ferrell
585 Robert Smigel
586 Billy Crystal
587 Peter Dinklage
588 Mark Ruffalo
589 Aziz Ansari
590 Jon Hamm
591 Steve Buscemi
592 Nick Offerman
593 Paul Rudd
594 Jake Gyllenhaal
595 Tom Cruise
596 Denis Leary

Question 6: Arrange the records in-order of date.

In [55]:
# arrange(data, desc(date))
arrange(data, date)

     year job                          date    category
1    2007 actress                      1/1/07  Acting
2    2007 author                       1/1/07  Media
3    2008 Author                       1/1/08  Media
4    2008 Consultant                   1/1/08  Political Aide
5    2008 television host              1/1/08  Media
6    2000 football player              1/10/00 Athletics
7    2001 singer                       1/10/01 Musician
8    2002 actor                        1/10/02 Acting
9    2005 lawyer                       1/10/05 Misc
10   2006 actor                        1/10/06 Acting
11   2007 former governor of arkansas  1/10/07 Politician
12   2008 television personality       1/10/08 Media
13   2011 actor                        1/10/11 Acting
14   2012 legal analyst                1/10/12 Misc
15   2013 actor                        1/10/13 Acting
16   2000 actor                        1/11/00 Acting
17   2001 actress                      1/11/01 Acting
18   2005 actor                        1/11/05 Acting
19   2006 Broadcaster                  1/11/06 Media
20   2007 Film actor                   1/11/07 Acting
21   2010 lawyer                       1/11/10 Misc
22   2011 actor                        1/11/11 Acting
23   2012 former us senator            1/11/12 Politician
24   1999 actor                        1/11/99 Acting
25   2000 rapper                       1/12/00 Musician
26   2004 Comedian                     1/12/04 Comedy
27   2005 actor                        1/12/05 Acting
28   2006 lawyer                       1/12/06 Misc
29   2009 author                       1/12/09 Media
30   2010 Editor                       1/12/10 Media
⋮    ⋮    ⋮                            ⋮       ⋮
2664 2010 singer-songwriter            9/30/10 Musician
2665 2013 television host              9/30/13 Media
2666 2014 actor                        9/30/14 Acting
2667 1999 actor                        9/30/99 Acting
2668 1999 comedian                     9/30/99 Comedy
2669 2008 Former Governor of Arkansas  9/4/08  Politician
2670 2012 Journalist                   9/4/12  Media
2671 2013 Astrophysicist               9/4/13  Science
2672 2014 singer-songwriter            9/4/14  Musician
2673 2000 film actor                   9/5/00  Acting
2674 2008 0                            9/5/08  NA
2675 2012 United States Senator        9/5/12  Politician
2676 2013 actor                        9/5/13  Acting
2677 2000 actor                        9/6/00  Acting
2678 2005 doctor                       9/6/05  Science
2679 2011 former governor of louisiana 9/6/11  Politician
2680 2012 economist                    9/6/12  Academic
2681 2000 Band                         9/7/00  Musician
2682 2005 actor                        9/7/05  Acting
2683 2010 Consultant                   9/7/10  Political Aide
2684 2011 neurosurgeon                 9/7/11  Science
2685 2012 NA                           9/7/12  NA
2686 2005 journalist                   9/8/05  Media
2687 2010 United States Senator        9/8/10  Politician
2688 2011 actress                      9/8/11  Acting
2689 2002 actress                      9/9/02  Acting
2690 2003 united states senator        9/9/03  Politician
2691 2010 Columnist                    9/9/10  Media
2692 2013 Journalist                   9/9/13  Media
2693 2014 United States Senator        9/9/14  Politician
     guest_name
1    Meryl Streep
2    Sam Sheridan
3    Peggy Noonan
4    Tim Gunn
5    Conan O'Brien
6    Joe Montana
7    Vitamin C
8    Jack Black
9    John Grisham
10   Albert Brooks
11   Fmr. Gov. Mike Huckabee
12   Lou Dobbs
13   Denis Leary
14   Andrew Napolitano
15   Josh Brolin
16   Will Ferrell
17   Julia Stiles
18   Samuel L. Jackson
19   Peter Bergen
20   Peter O'Toole
21   John Yoo
22   Colin Firth
23   Jim DeMint
24   Michael J. Fox
25   Ice Cube
26   Richard Lewis
27   Dennis Quaid
28   Edward Lazarus
29   Maxwell Kennedy
30   Paul Ingrassia
⋮    ⋮
2664 Justin Timberlake
2665 Bill O'Reilly
2666 Ben Affleck
2667 Bruce McCulloch and Mark McKinney
2668 Bruce McCulloch and Mark McKinney
2669 Mike Huckabee
2670 Tom Brokaw
2671 Mario Livio
2672 Adam Levine
2673 Donal Logue
2674 (no guest)
2675 Kirsten Gillibrand
2676 Michael C. Hall
2677 Greg Kinnear
2678 Dr. Marc Siegel
2679 Buddy Roemer
2680 Austan Goolsbee
2681 Spinal Tap
2682 Samuel L. Jackson
2683 Tim Gunn
2684 Dr. Sanjay Gupta
2685 none
2686 Brian Williams
2687 Tim Kaine
2688 Marion Cotillard
2689 Lorraine Bracco
2690 Al Franken
2691 Meghan McCain
2692 Sheri Fink
2693 Kirsten Gillibrand

Question 7: Add one column to the database with the name “Experience”. (Help: mutate() function in dplyr)

In [67]:
data <- mutate(data, Experience=10)
print(data['Experience'])

     Experience
1            10
2            10
3            10
4            10
5            10
6            10
7            10
8            10
9            10
10           10
11           10
12           10
13           10
14           10
15           10
16           10
17           10
18           10
19           10
20           10
21           10
22           10
23           10
24           10
25           10
26           10
27           10
28           10
29           10
30           10
31           10
32           10
33           10
34           10
35           10
36           10
37           10
38           10
39           10
40           10
41           10
42           10
43           10
44           10
45           10
46           10
47           10
48           10
49           10
50           10
51           10
52           10
53           10
54           10
55           10
56           10
57           10
58           10
59           10
60           10
61           10
62           10
63           10
64           10
65           10
66           10
67           10
68           10
69           10
70           10
71           10
72           10
73           10
74           10
75           10
76           10
77           10
78           10
79           10
80           10
81           10
82           10
83           10
84           10
85           10
86           10
87           10
88           10
89           10
90           10
91           10
92           10
93           10
94           10
95           10
96           10
97           10
98           10
99           10
100          10
101          10
102          10
103          10
104          10
105          10
106          10
107          10
108          10
109          10
110          10
111          10
112          10
113          10
114          10
115          10
116          10
117          10
118          10
119          10
120          10
121          10
122          10
123          10
124          10
125          10
126          10
127          10
128          10
129          10
130          10
131          10
132          10
133          10
134          10
135          10
136          10
137          10
138          10
139          10
140          10
141          10
142          10
143          10
144          10
145          10
146          10
147          10
148          10
149          10
150          10
151          10
152          10
153          10
154          10
155          10
156          10
157          10
158          10
159          10
160          10
161          10
162          10
163          10
164          10
165          10
166          10
167          10
168          10
169          10
170          10
171          10
172          10
173          10
174          10
175          10
176          10
177          10
178          10
179          10
180          10
181          10
182          10
183          10
184          10
185          10
186          10
187          10
188          10
189          10
190          10
191          10
192          10
193          10
194          10
195          10
196          10
197          10
198          10
199          10
200          10
201          10
202          10
203          10
204          10
205          10
206          10
207          10
208          10
209          10
210          10
211          10
212          10
213          10
214          10
215          10
216          10
217          10
218          10
219          10
220          10
221          10
222          10
223          10
224          10
225          10
226          10
227          10
228          10
229          10
230          10
231          10
232          10
233          10
234          10
235          10
236          10
237          10
238          10
239          10
240          10
241          10
242          10
243          10
244          10
245          10
246          10
247          10
248          10
249          10
250          10
251          10
252          10
253          10
254          10
255          10
256          10
257          10
258          10
259          10
260          10
261          10
262          10
263          10
264          10
265          10
266          10
267          10
268          10
269          10
270          10
271          10
272          10
273          10
274          10
275          10
276          10
277          10
278          10
279          10
280          10
281          10
282          10
283          10
284          10
285          10
286          10
287          10
288          10
289          10
290          10
291          10
292          10
293          10
294          10
295          10
296          10
297          10
298          10
299          10
300          10
301          10
302          10
303          10
304          10
305          10
306          10
307          10
308          10
309          10
310          10
311          10
312          10
313          10
314          10
315          10
316          10
317          10
318          10
319          10
320          10
321          10
322          10
323          10
324          10
325          10
326          10
327          10
328          10
329          10
330          10
331          10
332          10
333          10
334          10
335          10
336          10
337          10
338          10
339          10
340          10
341          10
342          10
343          10
344          10
345          10
346          10
347          10
348          10
349          10
350          10
351          10
352          10
353          10
354          10
355          10
356          10
357          10
358          10
359          10
360          10
361          10
362          10
363          10
364          10
365          10
366          10
367          10
368          10
369          10
370          10
371          10
372          10
373          10
374          10
375          10
376          10
377          10
378          10
379          10
380          10
381          10
382          10
383          10
384          10
385          10
386          10
387          10
388          10
389          10
390          10
391          10
392          10
393          10
394          10
395          10
396          10
397          10
398          10
399          10
400          10
401          10
402          10
403          10
404          10
405          10
406          10
407          10
408          10
409          10
410          10
411          10
412          10
413          10
414          10
415          10
416          10
417          10
418          10
419          10
420          10
421          10
422          10
423          10
424          10
425          10
426          10
427          10
428          10
429          10
430          10
431          10
432          10
433          10
434          10
435          10
436          10
437          10
438          10
439          10
440          10
441          10
442          10
443          10
444          10
445          10
446          10
447          10
448          10
449          10
450          10
451          10
452          10
453          10
454          10
455          10
456          10
457          10
458          10
459          10
460          10
461          10
462          10
463          10
464          10
465          10
466          10
467          10
468          10
469          10
470          10
471          10
472          10
473          10
474          10
475          10
476          10
477          10
478          10
479          10
480          10
481          10
482          10
483          10
484          10
485          10
486          10
487          10
488          10
489          10
490          10
491          10
492          10
493          10
494          10
495          10
496          10
497          10
498          10
499          10
500          10
501          10
502          10
503          10
504          10
505          10
506          10
507          10
508          10
509          10
510          10
511          10
512          10
513          10
514          10
515          10
516          10
517          10
518          10
519          10
520          10
521          10
522          10
523          10
524          10
525          10
526          10
527          10
528          10
529          10
530          10
531          10
532          10
533          10
534          10
535          10
536          10
537          10
538          10
539          10
540          10
541          10
542          10
543          10
544          10
545          10
546          10
547          10
548          10
549          10
550          10
551          10
552          10
553          10
554          10
555          10
556          10
557          10
558          10
559          10
560          10
561          10
562          10
563          10
564          10
565          10
566          10
567          10
568          10
569          10
570          10
571          10
572          10
573          10
574          10
575          10
576          10
577          10
578          10
579          10
580          10
581          10
582          10
583          10
584          10
585          10
586          10
587          10
588          10
589          10
590          10
591          10
592          10
593          10
594          10
595          10
596          10
597          10
598          10
599          10
600          10
601          10
602          10
603          10
604          10
605          10
606          10
607          10
608          10
609          10
610          10
611          10
612          10
613          10
614          10
615          10
616          10
617          10
618          10
619          10
620          10
621          10
622          10
623          10
624          10
625          10
626          10
627          10
628          10
629          10
630          10
631          10
632          10
633          10
634          10
635          10
636          10
637          10
638          10
639          10
640          10
641          10
642          10
643          10
644          10
645          10
646          10
647          10
648          10
649          10
650          10
651          10
652          10
653          10
654          10
655          10
656          10
657          10
658          10
659          10
660          10
661          10
662          10
663          10
664          10
665          10
666          10
667          10
668          10
669          10
670          10
671          10
672          10
673          10
674          10
675          10
676          10
677          10
678          10
679          10
680          10
681          10
682          10
683          10
684          10
685          10
686          10
687          10
688          10
689          10
690          10
691          10
692          10
693          10
694          10
695          10
696          10
697          10
698          10
699          10
700          10
701          10
702          10
703          10
704          10
705          10
706          10
707          10
708          10
709          10
710          10
711          10
712          10
713          10
714          10
715          10
716          10
717          10
718          10
719          10
720          10
721          10
722          10
723          10
724          10
725          10
726          10
727          10
728          10
729          10
730          10
731          10
732          10
733          10
734          10
735          10
736          10
737          10
738          10
739          10
740          10
741          10
742          10
743          10
744          10
745          10
746          10
747          10
748          10
749          10
750          10
751          10
752          10
753          10
754          10
755          10
756          10
757          10
758          10
759          10
760          10
761          10
762          10
763          10
764          10
765          10
766          10
767          10
768          10
769          10
770          10
771          10
772          10
773          10
774          10
775          10
776          10
777          10
778          10
779          10
780          10
781          10
782          10
783          10
784          10
785          10
786          10
787          10
788          10
789          10
790          10
791          10
792          10
793          10
794          10
795          10
796          10
797          10
798          10
799          10
800          10
801          10
802          10
803          10
804          10
805          10
806          10
807          10
808          10
809          10
810          10
811          10
812          10
813          10
814          10
815          10
816          10
817          10
818          10
819          10
820          10
821          10
822          10
823          10
824          10
825          10
826          10
827          10
828          10
829          10
830          10
831          10
832          10
833          10
834          10
835          10
836          10
837          10
838          10
839          10
840          10
841          10
842          10
843          10
844          10
845          10
846          10
847          10
848          10
849          10
850          10
851          10
852          10
853          10
854          10
855          10
856          10
857          10
858          10
859          10
860          10
861          10
862          10
863          10
864          10
865          10
866          10
867          10
868          10
869          10
870          10
871          10
872          10
873          10
874          10
875          10
876          10
877          10
878          10
879          10
880          10
881          10
882          10
883          10
884          10
885          10
886          10
887          10
888          10
889          10
890          10
891          10
892          10
893          10
894          10
895          10
896          10
897          10
898          10
899          10
900          10
901          10
902          10
903          10
904          10
905          10
906          10
907          10
908          10
909          10
910          10
911          10
912          10
913          10
914          10
915          10
916          10
917          10
918          10
919          10
920          10
921          10
922          10
923          10
924          10
925          10
926          10
927          10
928          10
929          10
930          10
931          10
932          10
933          10
934          10
935          10
936          10
937          10
938          10
939          10
940          10
941          10
942          10
943          10
944          10
945          10
946          10
947          10
948          10
949          10
950          10
951          10
952          10
953          10
954          10
955          10
956          10
957          10
958          10
959          10
960          10
961          10
962          10
963          10
964          10
965          10
966          10
967          10
968          10
969          10
970          10
971          10
972          10
973          10
974          10
975          10
976          10
977          10
978          10
979          10
980          10
981          10
982          10
983          10
984          10
985          10
986          10
987          10
988          10
989          10
990          10
991          10
992          10
993          10
994          10
995          10
996          10
997          10
998          10
999          10
1000         10
1001         10
1002         10
1003         10
1004         10
1005         10
1006         10
1007         10
1008         10
1009         10
1010         10
1011         10
1012         10
1013         10
1014         10
1015         10
1016         10
1017         10
1018         10
1019         10
1020         10
1021         10
1022         10
1023         10
1024         10
1025         10
1026         10
1027         10
1028         10
1029         10
1030         10
1031         10
1032         10
1033         10
1034         10
1035         10
1036         10
1037         10
1038         10
1039         10
1040         10
1041         10
1042         10
1043         10
1044         10
1045         10
1046         10
1047         10
1048         10
1049         10
1050         10
1051         10
1052         10
1053         10
1054         10
1055         10
1056         10
1057         10
1058         10
1059         10
1060         10
1061         10
1062         10
1063         10
1064         10
1065         10
1066         10
1067         10
1068         10
1069         10
1070         10
1071         10
1072         10
1073         10
1074         10
1075         10
1076         10
1077         10
1078         10
1079         10
1080         10
1081         10
1082         10
1083         10
1084         10
1085         10
1086         10
1087         10
1088         10
1089         10
1090         10
1091         10
1092         10
1093         10
1094         10
1095         10
1096         10
1097         10
1098         10
1099         10
1100         10
1101         10
1102         10
1103         10
1104         10
1105         10
1106         10
1107         10
1108         10
1109         10
1110         10
1111         10
1112         10
1113         10
1114         10
1115         10
1116         10
1117         10
1118         10
1119         10
1120         10
1121         10
1122         10
1123         10
1124         10
1125         10
1126         10
1127         10
1128         10
1129         10
1130         10
1131         10
1132         10
1133         10
1134         10
1135         10
1136         10
1137         10
1138         10
1139         10
1140         10
1141         10
1142         10
1143         10
1144         10
1145         10
1146         10
1147         10
1148         10
1149         10
1150         10
1151         10
1152         10
1153         10
1154         10
1155         10
1156         10
1157         10
1158         10
1159         10
1160         10
1161         10
1162         10
1163         10
1164         10
1165         10
1166         10
1167         10
1168         10
1169         10
1170         10
1171         10
1172         10
1173         10
1174         10
1175         10
1176         10
1177         10
1178         10
1179         10
1180         10
1181         10
1182         10
1183         10
1184         10
1185         10
1186         10
1187         10
1188         10
1189         10
1190         10
1191         10
1192         10
1193         10
1194         10
1195         10
1196         10
1197         10
1198         10
1199         10
1200         10
1201         10
1202         10
1203         10
1204         10
1205         10
1206         10
1207         10
1208         10
1209         10
1210         10
1211         10
1212         10
1213         10
1214         10
1215         10
1216         10
1217         10
1218         10
1219         10
1220         10
1221         10
1222         10
1223         10
1224         10
1225         10
1226         10
1227         10
1228         10
1229         10
1230         10
1231         10
1232         10
1233         10
1234         10
1235         10
1236         10
1237         10
1238         10
1239         10
1240         10
1241         10
1242         10
1243         10
1244         10
1245         10
1246         10
1247         10
1248         10
1249         10

In [76]:
data_2 <- data %>% rename(yEaR=year, exp=Experience)

In [77]:
data_2

     yEaR job                        Show     Group      Raw_Guest_List
1    1999 actor                      1/11/99  Acting     Michael J. Fox
2    1999 Comedian                   1/12/99  Comedy     Sandra Bernhard
3    1999 television actress         1/13/99  Acting     Tracey Ullman
4    1999 film actress               1/14/99  Acting     Gillian Anderson
5    1999 actor                      1/18/99  Acting     David Alan Grier
6    1999 actor                      1/19/99  Acting     William Baldwin
7    1999 Singer-lyricist            1/20/99  Musician   Michael Stipe
8    1999 model                      1/21/99  Media      Carmen Electra
9    1999 actor                      1/25/99  Acting     Matthew Lillard
10   1999 stand-up comedian          1/26/99  Comedy     David Cross
11   1999 actress                    1/27/99  Acting     Yasmine Bleeth
12   1999 actor                      1/28/99  Acting     D. L. Hughley
13   1999 television actress         10/18/99 Acting     Rebecca Gayheart
14   1999 Comedian                   10/19/99 Comedy     Steven Wright
15   1999 actress                    10/20/99 Acting     Amy Brenneman
16   1999 actress                    10/21/99 Acting     Melissa Gilbert
17   1999 actress                    10/25/99 Acting     Cathy Moriarty
18   1999 comedian                   10/26/99 Comedy     Louie Anderson
19   1999 actress                    10/27/99 Acting     Sarah Michelle Gellar
20   1999 Singer-songwriter          10/28/99 Musician   Melanie C
21   1999 actor                      10/4/99  Acting     Greg Proops
22   1999 television personality     10/5/99  Media      Maury Povich
23   1999 actress                    10/6/99  Acting     Brooke Shields
24   1999 Comic                      10/7/99  Comedy     Molly Shannon
25   1999 actor                      11/1/99  Acting     Chris O'Donnell
26   1999 actress                    11/15/99 Acting     Christina Ricci
27   1999 Singer-songwriter          11/16/99 Musician   Tori Amos
28   1999 actress                    11/17/99 Acting     Yasmine Bleeth
29   1999 comedian                   11/18/99 Comedy     Bill Maher
30   1999 actress                    11/2/99  Acting     Jennifer Love Hewitt
⋮    ⋮    ⋮                          ⋮        ⋮          ⋮
2664 2015 stand-up comedian          6/10/15  Comedy     Colin Quinn
2665 2015 actor                      6/11/15  Acting     Mark Ruffalo
2666 2015 screenwriter               6/15/15  Media      Judd Apatow
2667 2015 actor                      6/16/15  Acting     Aziz Ansari
2668 2015 us president               6/17/15  Politician Bill Clinton
2669 2015 activist                   6/18/15  Advocacy   Malala Yousafzai
2670 2015 nyc mayor                  6/2/15   Politician Bill de Blasio
2671 2015 united states senator      6/22/15  Politician Al Franken
2672 2015 television Series Creator  6/23/15  Media      Seth MacFarlane
2673 2015 legal analyst              6/24/15  Misc       Andrew Napolitano
2674 2015 Comedian                   6/25/15  Comedy     Richard Lewis
2675 2015 actress                    6/29/15  Acting     Taylor Schilling
2676 2015 actress                    6/3/15   Acting     Melissa McCarthy
2677 2015 actor                      6/30/15  Acting     Jon Hamm
2678 2015 actor                      6/4/15   Acting     Steve Buscemi
2679 2015 First Minister of Scotland 6/8/15   Politician Nicola Sturgeon
2680 2015 actor                      6/9/15   Acting     Nick Offerman
2681 2015 United States Senator      7/1/15   Politician Kirsten Gillibrand
2682 2015 Author                     7/2/15   Media      Sarah Vowell
2683 2015 actor                      7/20/15  Acting     Paul Rudd
2684 2015 us president               7/21/15  Politician Barack Obama
2685 2015 actor                      7/22/15  Acting     Jake Gyllenhaal
2686 2015 Writer                     7/23/15  Media      Ta-Nehisi Coates
2687 2015 author                     7/27/15  Media      David McCullough
2688 2015 actor                      7/28/15  Acting     Tom Cruise
2689 2015 biographer                 7/29/15  Media      Doris Kearns Goodwin
2690 2015 director                   7/30/15  Media      J. J. Abrams
2691 2015 stand-up comedian          8/3/15   Comedy     Amy Schumer
2692 2015 actor                      8/4/15   Acting     Denis Leary
2693 2015 comedian                   8/5/15   Comedy     Louis C.K.
     exp
1    10
2    10
3    10
4    10
5    10
6    10
7    10
8    10
9    10
10   10
11   10
12   10
13   10
14   10
15   10
16   10
17   10
18   10
19   10
20   10
21   10
22   10
23   10
24   10
25   10
26   10
27   10
28   10
29   10
30   10
⋮    ⋮
2664 10
2665 10
2666 10
2667 10
2668 10
2669 10
2670 10
2671 10
2672 10
2673 10
2674 10
2675 10
2676 10
2677 10
2678 10
2679 10
2680 10
2681 10
2682 10
2683 10
2684 10
2685 10
2686 10
2687 10
2688 10
2689 10
2690 10
2691 10
2692 10
2693 10