In [1]:
v1 <- c(1, 2, 3)
v2 <- c(4, 5, 6)
v3 <- c(7, 8, 9)

In [3]:
cbind(v1, v2, v2)

     v1 v2 v2
[1,] 1  4  4
[2,] 2  5  5
[3,] 3  6  6

In [6]:
matrix(1:9, nrow=3, ncol=3, byrow=TRUE)

     [,1] [,2] [,3]
[1,] 1    2    3
[2,] 4    5    6
[3,] 7    8    9

In [10]:
f <- as.factor(c("Yes", "No", "Yes"))

In [12]:
table(f)

f
 No Yes
  1   2

In [13]:
levels(f)

[1] "No"  "Yes"

In [14]:
nlevels(f)

[1] 2

In [15]:
unclass(f)

[1] 2 1 2
attr(,"levels")
[1] "No"  "Yes"

In [16]:
df <- data.frame(a=1:3, b=c(T,F,T))

In [17]:
df

  a b
1 1  TRUE
2 2 FALSE
3 3  TRUE

In [18]:
x <- 1:3

In [19]:
names(x)

NULL

In [20]:
names(x) <- c("Foo", "bar", "foobar")

In [21]:
names(x)

[1] "Foo"    "bar"    "foobar"

In [22]:
x

   Foo    bar foobar
     1      2      3

In [23]:
class(x)

[1] "integer"

In [25]:
x['Foo']

Foo
  1

In [26]:
L <- list(a=1:3, b=4:6)

In [27]:
L

$a
[1] 1 2 3

$b
[1] 4 5 6

In [28]:
L[a]

ERROR: Error: object 'a' not found

In [29]:
L['a']

$a
[1] 1 2 3

In [30]:
L[['a']]

[1] 1 2 3

In [31]:
L[[1]]

[1] 1 2 3

In [32]:
L

$a
[1] 1 2 3

$b
[1] 4 5 6

In [33]:
df <- data.frame(a=1:3, b=4:6)

In [34]:
df

  a b
1 1 4
2 2 5
3 3 6

In [35]:
L[[1]][1]

[1] 1

In [36]:
L[[1]]

[1] 1 2 3

In [37]:
L$a

[1] 1 2 3

In [38]:
L$a[1]

[1] 1

In [39]:
v1 <- c(1, 2, 3)
v2 <- c(NA, 4, 5)
v3 <- c(6, NA, 7)

In [40]:
mat <- cbind(v1, v2, v3)

In [41]:
mat

     v1 v2 v3
[1,] 1  NA  6
[2,] 2   4 NA
[3,] 3   5  7

In [48]:
x <- list(aa=1:3, ab=1:4)

In [51]:
x$a

NULL

In [52]:
ma <- matrix(1:4, nrow=2, ncol=2)

In [54]:
dimnames(ma)

NULL

In [55]:
dimnames(ma) <- list(c("a", "b"), c("c", "d"))

In [58]:
dimnames(ma)

[[1]]
[1] "a" "b"

[[2]]
[1] "c" "d"

In [59]:
x <- c("a", "b", "c", "d", "a")
u <- x > "a"

In [60]:
u

[1] FALSE  TRUE  TRUE  TRUE FALSE

In [61]:
x[u]

[1] "b" "c" "d"

In [62]:
x <-list(foo = 1:4, bar = 0.6, baz = "hello")
x[c(1, 3)]

$foo
[1] 1 2 3 4

$baz
[1] "hello"

In [79]:
x <- list(foo = 1:4, bar = 0.6)
x$foo

[1] 1 2 3 4

In [84]:
x <- list(foo = 1:4, bar = 0.6)
x[[1]]
x[1]

x$foo

x[['bar']]
x[x <- list(foo = 1:4, bar = 0.6, baz = "hello")
name <- "foo"
x[[name]]
'bar']

[1] 1 2 3 4

$foo
[1] 1 2 3 4

[1] 1 2 3 4

[1] 0.6

$bar
[1] 0.6

In [91]:
x <-list(foo = 1:4, bar = 0.6, baz = "hello")
x[[1]][[3]]

[1] 3

In [92]:
x <-list(a = list(10, 12, 14), b = c(3.14, 2.81))
x[[c(1, 3)]]

[1] 14

In [100]:
x[[1]][[3]]

[1] 14

In [102]:
x <- list(a="abc", b=12)

In [109]:
x[[1]]
class(x[[1]])

x[[1]]

[1] "abc"

[1] "character"

[1] "abc"

In [110]:
a <- "abc"

In [123]:
x <- c(1, 2, NA, 4, NA, 5)
bad <- is.na(x)
bad

x[!bad]

[1] FALSE FALSE  TRUE FALSE  TRUE FALSE

[1] 1 2 4 5

In [120]:
x[["a"]]

NULL

In [127]:
x <- c(1, 2, 6, 4, NA, 5)
y <- c("a", "b", NA, "d", NA, "f")
good <- complete.cases(x, y)
good

[1]  TRUE  TRUE FALSE  TRUE FALSE  TRUE

In [141]:
x <- 1:3

In [142]:
median(x)

[1] 2

In [143]:
A <- c(1, 2, 3)
B <- c(4, 5, 6)
C <- c(7, 8, 9)

In [144]:
rw <- rbind(A, B, C)

In [145]:
rw

  [,1] [,2] [,3]
A 1    2    3
B 4    5    6
C 7    8    9

In [146]:
rw[3, ]

[1] 7 8 9

In [148]:
rw[3]

[1] 7

In [149]:
cw <- cbind(A, B, C)

In [150]:
print(cw)

     A B C
[1,] 1 4 7
[2,] 2 5 8
[3,] 3 6 9

  Write R code to generate the following vectors, explore the functions seq() and rep() using the help on commands
  - 1.3 1.6 1.9 2.2 2.5 2.8 3.1 3.4 3.7 4.0 4.3 4.6 4.9
  - 1 2 3 4 1 2 3 4 1 2 3 4 1 2 3 4 1 2 3 4
  - 14 12 10 8 6 4 2 0
  - 5 5 12 12 13 13 20 20

In [151]:
s1 <- seq(1.3, 4.9, by=0.3)

In [152]:
s1

 [1] 1.3 1.6 1.9 2.2 2.5 2.8 3.1 3.4 3.7 4.0 4.3 4.6 4.9

In [157]:
s2 <- rep(1:4, 5)

In [158]:
s2

 [1] 1 2 3 4 1 2 3 4 1 2 3 4 1 2 3 4 1 2 3 4

In [159]:
s3 <- seq(14, 0, by=-2)

In [160]:
s3

[1] 14 12 10  8  6  4  2  0

In [161]:
s4 <- rep(c(5, 12, 13, 20), each=2)

In [162]:
s4

[1]  5  5 12 12 13 13 20 20

  Loading and exploring data structure Load the iris data that R provides internally by typing data(iris) 
  + What sort of data type is iris?
  + How many rows (observations) and columns (variables) does the iris dataset have?
  + Which variable of the data frame iris is a factor and how many levels does it have?
    + The variable Species is a factor and it has 5 levels.
    + The variable Species is a factor and it has 3 levels.
    + The variable 'data.frame' is a factor and it has 150 levels.
    + The variable 'data.frame' is a factor and it has 5 levels.

In [163]:
data(iris)

In [165]:
class(iris)

[1] "data.frame"

In [166]:
nrow(iris)
ncol(iris)

[1] 150

[1] 5

In [167]:
str(iris)

'data.frame':	150 obs. of  5 variables:
 $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
 $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
 $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
 $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
 $ Species     : Factor w/ 3 levels "setosa","versicolor",..: 1 1 1 1 1 1 1 1 1 1 ...

  Use the “iris” dataset to find 
  + The mean and standard deviation of the sepal width and sepal length for each type of species.
  + Create a new dataset called iris.class from the iris dataset. Use a loop and ifelse statement to create a vector in the iris.class dataset called Calyx.Width, which is “short” if Sepal.Length is less than 5, and otherwise is “long.” (The sepals of a flower are collectively known as the calyx.)

In [175]:
aggregate(cbind(iris$Sepal.Width, iris$Sepal.Length) ~ iris$Species, data=iris, FUN=mean)

  iris$Species V1    V2
1 setosa       3.428 5.006
2 versicolor   2.770 5.936
3 virginica    2.974 6.588

In [178]:
aggregate(cbind(iris$Sepal.Width, iris$Sepal.Length) ~ iris$Species, data=iris, FUN=sd)

  iris$Species V1        V2
1 setosa       0.3790644 0.3524897
2 versicolor   0.3137983 0.5161711
3 virginica    0.3224966 0.6358796

In [179]:
iris_class <- iris

In [180]:
iris_class

    Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1   5.1          3.5         1.4          0.2         setosa
2   4.9          3.0         1.4          0.2         setosa
3   4.7          3.2         1.3          0.2         setosa
4   4.6          3.1         1.5          0.2         setosa
5   5.0          3.6         1.4          0.2         setosa
6   5.4          3.9         1.7          0.4         setosa
7   4.6          3.4         1.4          0.3         setosa
8   5.0          3.4         1.5          0.2         setosa
9   4.4          2.9         1.4          0.2         setosa
10  4.9          3.1         1.5          0.1         setosa
11  5.4          3.7         1.5          0.2         setosa
12  4.8          3.4         1.6          0.2         setosa
13  4.8          3.0         1.4          0.1         setosa
14  4.3          3.0         1.1          0.1         setosa
15  5.8          4.0         1.2          0.2         setosa
16  5.7          4.4         1.5          0.4         setosa
17  5.4          3.9         1.3          0.4         setosa
18  5.1          3.5         1.4          0.3         setosa
19  5.7          3.8         1.7          0.3         setosa
20  5.1          3.8         1.5          0.3         setosa
21  5.4          3.4         1.7          0.2         setosa
22  5.1          3.7         1.5          0.4         setosa
23  4.6          3.6         1.0          0.2         setosa
24  5.1          3.3         1.7          0.5         setosa
25  4.8          3.4         1.9          0.2         setosa
26  5.0          3.0         1.6          0.2         setosa
27  5.0          3.4         1.6          0.4         setosa
28  5.2          3.5         1.5          0.2         setosa
29  5.2          3.4         1.4          0.2         setosa
30  4.7          3.2         1.6          0.2         setosa
⋮   ⋮            ⋮           ⋮            ⋮           ⋮
121 6.9          3.2         5.7          2.3         virginica
122 5.6          2.8         4.9          2.0         virginica
123 7.7          2.8         6.7          2.0         virginica
124 6.3          2.7         4.9          1.8         virginica
125 6.7          3.3         5.7          2.1         virginica
126 7.2          3.2         6.0          1.8         virginica
127 6.2          2.8         4.8          1.8         virginica
128 6.1          3.0         4.9          1.8         virginica
129 6.4          2.8         5.6          2.1         virginica
130 7.2          3.0         5.8          1.6         virginica
131 7.4          2.8         6.1          1.9         virginica
132 7.9          3.8         6.4          2.0         virginica
133 6.4          2.8         5.6          2.2         virginica
134 6.3          2.8         5.1          1.5         virginica
135 6.1          2.6         5.6          1.4         virginica
136 7.7          3.0         6.1          2.3         virginica
137 6.3          3.4         5.6          2.4         virginica
138 6.4          3.1         5.5          1.8         virginica
139 6.0          3.0         4.8          1.8         virginica
140 6.9          3.1         5.4          2.1         virginica
141 6.7          3.1         5.6          2.4         virginica
142 6.9          3.1         5.1          2.3         virginica
143 5.8          2.7         5.1          1.9         virginica
144 6.8          3.2         5.9          2.3         virginica
145 6.7          3.3         5.7          2.5         virginica
146 6.7          3.0         5.2          2.3         virginica
147 6.3          2.5         5.0          1.9         virginica
148 6.5          3.0         5.2          2.0         virginica
149 6.2          3.4         5.4          2.3         virginica
150 5.9          3.0         5.1          1.8         virginica

In [188]:
for (i in 1:nrow(iris)) {
    iris_class[i, 'Calyx.Width'] = ''

    if (iris$Sepal.Length[i] < 5) {
iris_class[i, 'Calyx.Width'] = 'short'
        }
    else {
iris_class[i, 'Calyx.Width'] = 'long'
        }
    }

In [189]:
iris_class$Calyx.Width

  [1] "long"  "short" "short" "short" "long"  "long"  "short" "long"  "short"
 [10] "short" "long"  "short" "short" "short" "long"  "long"  "long"  "long"
 [19] "long"  "long"  "long"  "long"  "short" "long"  "short" "long"  "long"
 [28] "long"  "long"  "short" "short" "long"  "long"  "long"  "short" "long"
 [37] "long"  "short" "short" "long"  "long"  "short" "short" "long"  "long"
 [46] "short" "long"  "short" "long"  "long"  "long"  "long"  "long"  "long"
 [55] "long"  "long"  "long"  "short" "long"  "long"  "long"  "long"  "long"
 [64] "long"  "long"  "long"  "long"  "long"  "long"  "long"  "long"  "long"
 [73] "long"  "long"  "long"  "long"  "long"  "long"  "long"  "long"  "long"
 [82] "long"  "long"  "long"  "long"  "long"  "long"  "long"  "long"  "long"
 [91] "long"  "long"  "long"  "long"  "long"  "long"  "long"  "long"  "long"
[100] "long"  "long"  "long"  "long"  "long"  "long"  "long"  "short" "long"
[109] "long"  "long"  "long"  "long"  "long"  "long"  "long"  "long"  "long"
[118] "long"  "long"  "long"  "long"  "long"  "long"  "long"  "long"  "long"
[127] "long"  "long"  "long"  "long"  "long"  "long"  "long"  "long"  "long"
[136] "long"  "long"  "long"  "long"  "long"  "long"  "long"  "long"  "long"
[145] "long"  "long"  "long"  "long"  "long"  "long"

  Explore dataset- mtcars in R. You can get the structure and column names of data by typing the command str(mtcars) and names(mtcars) respectively. Write your code to subset the dataset- mtcars according to the following requirements
  + Select cars whose cyl (a column in the dataset) value is no smaller than 5.
  + Show all the fields (columns) of the first 10 cars.
  + Find all cars matching “Honda”
  + Find the average miles per gallon (mpg) for all number of cylinders.

In [196]:
attach(mtcars)

In [197]:
str(mtcars)

'data.frame':	32 obs. of  11 variables:
 $ mpg : num  21 21 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 ...
 $ cyl : num  6 6 4 6 8 6 8 4 4 6 ...
 $ disp: num  160 160 108 258 360 ...
 $ hp  : num  110 110 93 110 175 105 245 62 95 123 ...
 $ drat: num  3.9 3.9 3.85 3.08 3.15 2.76 3.21 3.69 3.92 3.92 ...
 $ wt  : num  2.62 2.88 2.32 3.21 3.44 ...
 $ qsec: num  16.5 17 18.6 19.4 17 ...
 $ vs  : num  0 0 1 1 0 1 0 1 1 1 ...
 $ am  : num  1 1 1 0 0 0 0 0 0 0 ...
 $ gear: num  4 4 4 3 3 3 3 4 4 4 ...
 $ carb: num  4 4 1 1 2 1 4 2 2 4 ...

In [221]:
# subset(mtcars, cyl > 5, select=cyl)
mtcars[mtcars$cyl > 5, ]

                    mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Mazda RX4           21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4
Mazda RX4 Wag       21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4
Hornet 4 Drive      21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1
Hornet Sportabout   18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2
Valiant             18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1
Duster 360          14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4
Merc 280            19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4
Merc 280C           17.8 6   167.6 123 3.92 3.440 18.90 1  0  4    4
Merc 450SE          16.4 8   275.8 180 3.07 4.070 17.40 0  0  3    3
Merc 450SL          17.3 8   275.8 180 3.07 3.730 17.60 0  0  3    3
Merc 450SLC         15.2 8   275.8 180 3.07 3.780 18.00 0  0  3    3
Cadillac Fleetwood  10.4 8   472.0 205 2.93 5.250 17.98 0  0  3    4
Lincoln Continental 10.4 8   460.0 215 3.00 5.424 17.82 0  0  3    4
Chrysler Imperial   14.7 8   440.0 230 3.23 5.345 17.42 0  0  3    4
Dodge Challenger    15.5 8   318.0 150 2.76 3.520 16.87 0  0  3    2
AMC Javelin         15.2 8   304.0 150 3.15 3.435 17.30 0  0  3    2
Camaro Z28          13.3 8   350.0 245 3.73 3.840 15.41 0  0  3    4
Pontiac Firebird    19.2 8   400.0 175 3.08 3.845 17.05 0  0  3    2
Ford Pantera L      15.8 8   351.0 264 4.22 3.170 14.50 0  1  5    4
Ferrari Dino        19.7 6   145.0 175 3.62 2.770 15.50 0  1  5    6
Maserati Bora       15.0 8   301.0 335 3.54 3.570 14.60 0  1  5    8

In [230]:
head(mtcars, 150)

                    mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Mazda RX4           21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4
Mazda RX4 Wag       21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4
Datsun 710          22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1
Hornet 4 Drive      21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1
Hornet Sportabout   18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2
Valiant             18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1
Duster 360          14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4
Merc 240D           24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2
Merc 230            22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2
Merc 280            19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4
Merc 280C           17.8 6   167.6 123 3.92 3.440 18.90 1  0  4    4
Merc 450SE          16.4 8   275.8 180 3.07 4.070 17.40 0  0  3    3
Merc 450SL          17.3 8   275.8 180 3.07 3.730 17.60 0  0  3    3
Merc 450SLC         15.2 8   275.8 180 3.07 3.780 18.00 0  0  3    3
Cadillac Fleetwood  10.4 8   472.0 205 2.93 5.250 17.98 0  0  3    4
Lincoln Continental 10.4 8   460.0 215 3.00 5.424 17.82 0  0  3    4
Chrysler Imperial   14.7 8   440.0 230 3.23 5.345 17.42 0  0  3    4
Fiat 128            32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1
Honda Civic         30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2
Toyota Corolla      33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1
Toyota Corona       21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1
Dodge Challenger    15.5 8   318.0 150 2.76 3.520 16.87 0  0  3    2
AMC Javelin         15.2 8   304.0 150 3.15 3.435 17.30 0  0  3    2
Camaro Z28          13.3 8   350.0 245 3.73 3.840 15.41 0  0  3    4
Pontiac Firebird    19.2 8   400.0 175 3.08 3.845 17.05 0  0  3    2
Fiat X1-9           27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1
Porsche 914-2       26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2
Lotus Europa        30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2
Ford Pantera L      15.8 8   351.0 264 4.22 3.170 14.50 0  1  5    4
Ferrari Dino        19.7 6   145.0 175 3.62 2.770 15.50 0  1  5    6
Maserati Bora       15.0 8   301.0 335 3.54 3.570 14.60 0  1  5    8
Volvo 142E          21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2

In [223]:
grep("Honda", mtcars[1])

integer(0)

In [254]:
mtcars[grep("Merc", rownames(mtcars)), -mtcars$mpg]
# grep("Merc", rownames(mtcars), value=TRUE)

# subset(mtcars, as.logical(grep("Merc", rownames(mtcars))))

            mpg  cyl disp  hp  drat wt   qsec vs am carb
Merc 240D   24.4 4   146.7  62 3.69 3.19 20.0 1  0  2
Merc 230    22.8 4   140.8  95 3.92 3.15 22.9 1  0  2
Merc 280    19.2 6   167.6 123 3.92 3.44 18.3 1  0  4
Merc 280C   17.8 6   167.6 123 3.92 3.44 18.9 1  0  4
Merc 450SE  16.4 8   275.8 180 3.07 4.07 17.4 0  0  3
Merc 450SL  17.3 8   275.8 180 3.07 3.73 17.6 0  0  3
Merc 450SLC 15.2 8   275.8 180 3.07 3.78 18.0 0  0  3

In [257]:
aggregate(mpg ~ cyl, data=mtcars, FUN=mean)

  cyl mpg
1 4   26.66364
2 6   19.74286
3 8   15.10000

In [262]:
x <- 1:20
print(x)

print(x[-2])
print(x[-2:-5])

 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20
 [1]  1  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20
 [1]  1  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20

In [263]:
df <- data.frame(PatientID=1:4, AdmDate=c('10/15/2009', '11/01/2009', '10/21/2009', '10/28/2009'), Age=c(25, 34, 28, 52), Diabetes=c('Type1', 'Type2', 'Type1', 'Type1'), Status=c("Poor", "Improved", "Excellent", "Poor"))

In [264]:
df

  PatientID AdmDate    Age Diabetes Status
1 1         10/15/2009 25  Type1    Poor
2 2         11/01/2009 34  Type2    Improved
3 3         10/21/2009 28  Type1    Excellent
4 4         10/28/2009 52  Type1    Poor

In [272]:
# subset1 <- df[c(1, 2)]
subset1 <- df[c('PatientID', 'Age')]
print(subset1)

  PatientID Age
1         1  25
2         2  34
3         3  28
4         4  52

In [283]:
subset(df, df$Diabetes == "Type1",)

  PatientID AdmDate    Age Diabetes Status
1 1         10/15/2009 25  Type1    Poor
3 3         10/21/2009 28  Type1    Excellent
4 4         10/28/2009 52  Type1    Poor

In [288]:
summary(df)

   PatientID      AdmDate               Age          Diabetes
 Min.   :1.00   Length:4           Min.   :25.00   Length:4
 1st Qu.:1.75   Class :character   1st Qu.:27.25   Class :character
 Median :2.50   Mode  :character   Median :31.00   Mode  :character
 Mean   :2.50                      Mean   :34.75
 3rd Qu.:3.25                      3rd Qu.:38.50
 Max.   :4.00                      Max.   :52.00
    Status
 Length:4
 Class :character
 Mode  :character

In [293]:
aggregate(Age ~ Diabetes, FUN=mean, data=df)

mean(df$Age)

  Diabetes Age
1 Type1    35
2 Type2    34

[1] 34.75

In [313]:
MyList <- list(title="My First List", criteria=list(
    age=c(12,14,16,20),
    mat=matrix(1:5, nrow=5, ncol=3),
    score=c("First", "Second", "Third")
))

# print(MyList)
# print(MyList$criteria)
print(MyList$criteria$age)

[1] 12 14 16 20

In [328]:
add <- function(...) {
     args <- c(...)
    sum(args)
    }

print(add(3, 5, 11, 24))

[1] 43

In [341]:
x <- 10
n <- 5

make.power <- function(n) {
  pow <- function(x) {
    x^n
  }
  pow}

cube <- make.power(3)
square <- make.power(2)
cube(3)
square(3)


ls(environment(cube))
get("n", environment(cube))

[1] 27

[1] 9

[1] "n"   "pow"

[1] 3

In [342]:
get("pow", environment(cube))

function (x)
{
    x^n
}
<environment: 0x56313d929160>

In [343]:
x <- 1:4; y <- 6:9
x + y

[1]  7  9 11 13

In [346]:
x > 2
x >= 2
 x * y

[1] FALSE FALSE  TRUE  TRUE

[1] FALSE  TRUE  TRUE  TRUE

[1]  6 14 24 36

In [348]:
x <- matrix(1:4, 2, 2)
y <- matrix(rep(10, 4), 2, 2)

In [350]:
 x * y  ## element-wise multiplication
x %*% y

     [,1] [,2]
[1,] 10   30
[2,] 20   40

     [,1] [,2]
[1,] 40   40
[2,] 60   60

In [360]:
x <- as.POSIXct("1970/01/01")
x

unclass(x)

 x <- Sys.time()
 x


p <- as.POSIXlt(x)
p
names(unclass(p))
x <- as.Date("2012-01-01")
y <- strptime("9 January 2011 11:34:21", "%d %b %Y %H:%M:%S")
x-y # This line is commented only to generate pdf. Before testing uncomment it.

[1] "1970-01-01 IST"

[1] -19800
attr(,"tzone")
[1] ""

[1] "2025-09-23 12:15:23 IST"

[1] "2025-09-23 12:15:23 IST"

 [1] "sec"    "min"    "hour"   "mday"   "mon"    "year"   "wday"   "yday"
 [9] "isdst"  "zone"   "gmtoff"

In [362]:
x <- as.Date("2012-01-01")
y <- strptime("9 January 2011 11:34:21", "%d %b %Y %H:%M:%S")
x-y

Warning message:
“Incompatible methods ("-.Date", "-.POSIXt") for "-"”

ERROR: Error in x - y: non-numeric argument to binary operator

In [366]:
x <- as.Date("2012-03-01"); y <- as.Date("2012-02-28")
x-y

Time difference of 2 days

In [364]:
x <- as.POSIXct("2012-10-25 01:00:00")
y <- as.POSIXct("2012-10-25 06:00:00", tz = "GMT")
y-x

Time difference of 10.5 hours

In [369]:
my_matrix <- matrix(1:9, nrow = 3, ncol = 3)
my_matrix
row_sums <- apply(my_matrix, 2, sum) # 1 indicates rows

print(row_sums)

     [,1] [,2] [,3]
[1,] 1    4    7
[2,] 2    5    8
[3,] 3    6    9

[1]  6 15 24

In [375]:
# Calculate the length of each string in a list
my_list <- list(a = "apple", b = "banana", c = "cherry")
lengths <- lapply(my_list, nchar)
print(lengths) # This will print the lengths of each string in the list
class(lengths)

$a
[1] 5

$b
[1] 6

$c
[1] 6

[1] "list"

In [376]:
# Calculate the length of each string in a list
my_list <- list(a = "apple", b = "banana", c = "cherry")
lengths <- sapply(my_list, nchar)
print(lengths) # This will print the lengths of each string in the list
class(lengths)

a b c
5 6 6

[1] "integer"

In [377]:
attach(iris)

In [379]:
mean_sepal_length <- tapply(iris$Sepal.Length, iris$Species, mean)
print(mean_sepal_length) # This will print the mean Sepal.Length for each Species
# Example: Split the iris dataset by Species
split_iris <- split(iris, iris$Species)
print(split_iris) # This will print the list of data frames split by Species

    setosa versicolor  virginica
     5.006      5.936      6.588

In [382]:
# Example: Split the iris dataset by Species
split_iris <- split(iris, iris$Species)
# print(split_iris) # This will print the list of data frames split by Species

print(names(split_iris))

print(split_iris$setosa)

[1] "setosa"     "versicolor" "virginica"
   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1           5.1         3.5          1.4         0.2  setosa
2           4.9         3.0          1.4         0.2  setosa
3           4.7         3.2          1.3         0.2  setosa
4           4.6         3.1          1.5         0.2  setosa
5           5.0         3.6          1.4         0.2  setosa
6           5.4         3.9          1.7         0.4  setosa
7           4.6         3.4          1.4         0.3  setosa
8           5.0         3.4          1.5         0.2  setosa
9           4.4         2.9          1.4         0.2  setosa
10          4.9         3.1          1.5         0.1  setosa
11          5.4         3.7          1.5         0.2  setosa
12          4.8         3.4          1.6         0.2  setosa
13          4.8         3.0          1.4         0.1  setosa
14          4.3         3.0          1.1         0.1  setosa
15          5.8         4.0          1.2         0.2  setosa
16          5.7         4.4          1.5         0.4  setosa
17          5.4         3.9          1.3         0.4  setosa
18          5.1         3.5          1.4         0.3  setosa
19          5.7         3.8          1.7         0.3  setosa
20          5.1         3.8          1.5         0.3  setosa
21          5.4         3.4          1.7         0.2  setosa
22          5.1         3.7          1.5         0.4  setosa
23          4.6         3.6          1.0         0.2  setosa
24          5.1         3.3          1.7         0.5  setosa
25          4.8         3.4          1.9         0.2  setosa
26          5.0         3.0          1.6         0.2  setosa
27          5.0         3.4          1.6         0.4  setosa
28          5.2         3.5          1.5         0.2  setosa
29          5.2         3.4          1.4         0.2  setosa
30          4.7         3.2          1.6         0.2  setosa
31          4.8         3.1          1.6         0.2  setosa
32          5.4         3.4          1.5         0.4  setosa
33          5.2         4.1          1.5         0.1  setosa
34          5.5         4.2          1.4         0.2  setosa
35          4.9         3.1          1.5         0.2  setosa
36          5.0         3.2          1.2         0.2  setosa
37          5.5         3.5          1.3         0.2  setosa
38          4.9         3.6          1.4         0.1  setosa
39          4.4         3.0          1.3         0.2  setosa
40          5.1         3.4          1.5         0.2  setosa
41          5.0         3.5          1.3         0.3  setosa
42          4.5         2.3          1.3         0.3  setosa
43          4.4         3.2          1.3         0.2  setosa
44          5.0         3.5          1.6         0.6  setosa
45          5.1         3.8          1.9         0.4  setosa
46          4.8         3.0          1.4         0.3  setosa
47          5.1         3.8          1.6         0.2  setosa
48          4.6         3.2          1.4         0.2  setosa
49          5.3         3.7          1.5         0.2  setosa
50          5.0         3.3          1.4         0.2  setosa

In [383]:
x <- c(rnorm(10), runif(10), rnorm(10, 1))
f <- gl(3, 10) 
split(x, f)

$`1`
 [1] -0.2135226  0.9056123  0.9574412 -0.8942354 -0.9171975  1.2575566
 [7]  2.0564942 -0.8294601 -0.6194659  0.9606920

$`2`
 [1] 0.980589839 0.164427554 0.006455786 0.010858180 0.233518858 0.001836218
 [7] 0.547890608 0.225649255 0.564820174 0.054309950

$`3`
 [1]  1.5240248  1.2749863  0.8250261  1.1863684  0.5444685 -0.2924512
 [7]  1.1809808  1.4674738  0.4167658  1.3638693

In [385]:
x <- gl(2, 8, labels = c("Control", "Treat"))

In [386]:
x

 [1] Control Control Control Control Control Control Control Control Treat
[10] Treat   Treat   Treat   Treat   Treat   Treat   Treat
Levels: Control Treat

In [388]:
df <- data.frame(a=c(1, 2), b=c(3, 4), c=c(5, 6))
df

  a b c
1 1 3 5
2 2 4 6

In [395]:
new_data <- data.frame(
		       a=as.numeric(readline("Enter a number")), 
		       b=as.numeric(readline("Enter a number")), 
		       c=as.numeric(readline("Enter a number"))
)

df[nrow(df)+1, ] = new_data
print(df)

Enter a number 10
Enter a number 20
Enter a number 30

   a  b  c
1  1  3  5
2  2  4  6
3 20 30 24
4 10 20 30

In [406]:
data= matrix(c(1:16), ncol=4, byrow=TRUE)

# specify the column names and row names of matrix
colnames(data) = c('col1','col2','col3','col4')
rownames(data) <- c('row1','row2','row3','row4')

# assign to table
final=as.table(data)

In [413]:
final
write.table(final, 
            file = "abc1.txt")

# write.csv("hello world", file="abc1.txt")

     col1 col2 col3 col4
row1    1    2    3    4
row2    5    6    7    8
row3    9   10   11   12
row4   13   14   15   16

In [414]:
read.table("abc1.txt")
# write.table("Hello world", file="abc1.txt")

     col1 col2 col3 col4
row1  1    2    3    4
row2  5    6    7    8
row3  9   10   11   12
row4 13   14   15   16

In [404]:
list.files()

 [1] "abc1.txt"       "compile.sh"     "final.pdf"      "lab_01"
 [5] "lab_02"         "lab_03"         "lab_04"         "lab_05"
 [9] "lab_06"         "lab_07"         "lab_08"         "test.md"
[13] "Untitled.ipynb"

In [403]:
file.create("abc1.txt")

[1] TRUE